- ngengesenior.js
> Added ngengesenor.js

- github_akashraj98.js
> Created github_akshraj98.js

- package.json
run `npm test` to evaluate all ` *.js` files. 
Configure `package.json` under `"scripts"` to add all files/folders
> Added StandardJS to be used for eslint

- studentdawid.js
> #1 Add myself to repo

- ihwanid.js
Halo mas Irfan :) Semoga sehat sekeluarga
> add ihwanid

- vaticori.js
I dont have a facebook or a linkedin sadly
> Added my information

- peoples/madison-boman.js
added madison-boman to persons
> Added madison-boman to persons

- peoples/shhzdmrz.js
added my name to repo issue #1
> added my name to repo

- peoples/brunohgv.js
> Now i have my name

- peoples/DwarfThief.js
> Hello Open Source

- peoples/dishantak.js
Added new JS file to update with my github information
> added Dishanta

- peoples/highdesert09.js
>  added user

- myname.txt
> add my name to this repo

- peoples/github_darolab1111.js
> I follow the step in README.md

- M-M
> This is my information.

- peoples/rs094.js
> Create file and update info

- peoples/jeevanpuchakay.js
I've added a file named jeevnpuckay.js
> Addition of jeevanpuchakay.js file

- peoples/github_rohanmd07.js
> Created github_rohanmd07.js

- peoples/orga-itsuka.js
> Add new people in list

- peoples/githubRisyandi.js
Hi Mas Irfan,
Please review this PR for Hacktober fun. 🎉 
Thanks a lot.
> add new people

- peoples/github_abdulMuhit.js
learn and add my data to contribute in this opensource project.
> adding my data

- peoples/gerald.js
halo mas @mazipan 
i want to add gerald.js to hello-open-source  ^_^
> add user gerald

- peoples/barrosdaniel.js
Add the barrosdaniel.js profile
> feature: Add barrosdaniel profile

- peoples/sav7204.js
Created sav7204.js and place in file People/
> Created sav7204.js

- peoples/github_jpedroSM.js
> Add jpedro sm.js

- peoples/imsonujangra.js
@mazipan check my pull request.
> add my profile to people directory

- README.md
- package.json
- purge.js
* **Added** a script that will purge the file for specified users or ALL users if no user is specified
FIXES #96
> Added script to purge name or all files

- peoples/diksha.js
Added my details in new js file :)
> added my details

- peoples/tarunsingal1409
This is my first github commit
> creating first github file

- peoples/richa101
> merge richa101

- peoples/diego.js
> Added my file

- peoples/github_tmbharathiraja.js
> Open Source contribution trail

- peoples/TomFrink.js
First Pull Request for #HACKTOBERFEST
> Added Tom's File

- peoples/imamaris.js
Adding file imamaris.js for open source hacktoberfest 2019
> Adding File : imamaris.js in list

- peoples/ishitar.js
Have added the file ishitar.js in /peoples.
> Added ishitar.js

- peoples/valdemirfilho.js
Add Valdemir Filho to peoples directory
> Add Valdemir Filho

- peoples/add-JukMR.js
> Add people/JukMR.js

- peoples/denni5lin.js
> Add dlin's info

- peoples/superyassh.js
Created superyassh.js in peoples/ directory and added my Detail in that.
> Added my Detail

- peoples/hjwlpjr.js
contribute and make PR by adding hjwlpjr.js
> add hjwlpjr data

- peoples/kunalraghav.js
Added KunalRaghav.js with all the necessary details
> contribution complete

- peoples/vpatil.js
> Added .js file

- drunkedMonkey.js
> drunkedMonkey info

- peoples/rithgan.js
Add rithgan.js. Thanks for the oppurtunity.
> Add rithgan.js to peoples

- peoples/haidarrifki.js
> added new peoples

- peoples/technickel.js
This is great practice for forking projects, creating branches, and submitting pull requests!
> Added name to repo

- README-PT-BR.md
Hi, I'm adding a Portuguese translator of this README.md repository. Some ppl who live here in Brazil don't understand very well English! I hope it helps more ppl to understand the Open Source' flow.
> adding portuguese translator for README.md

- peoples/prince.js
> added myself

- README-ID.md
add indonesian translations to README.MD
> add indonesian translations

- peoples/blackmenthor.js
added blackmenthor.js inside people folder
> add Blackmenthor js

- peoples/leeconnelly12.js
> added name

- README-DE.md
- README-ID.md
- README.md
- peoples/bitwire.js
This PR adds a German Translation of the README, links in every README with links to the other translations and my own Info in peoples.
> Adds German Translation and bitwire in people directory

- README-ES.md
Actualización de gramática y corrección de signos de puntuación.
> [update] README-ES.md

- peoples/sp4ceunicorn.js
Added my data to the peoples folder!
> Added my data

- peoples/elloa.js
I do not have profile on social networks
> add-elloa.js

- peoples/github_psy0ch.js
> add contributer

- peoples/arpadracz.js
Added a new .js file.
First open source PR. #Hacktoberfest
> Add myself to the peoples dir

- peoples/eaquin1.js
Hi this is my first pull request, thanks for making this repository!
> add eaquin1

- peoples/kcmvillarino.js
Please check my pull request! Thanks :)
> Added kcmvillarino.js

- peoples/vinita.js
Added my info to the peoples folder!
> Added my info

- peoples/gauravburjwal.js
Followed all the steps. Waiting for PR to be merged :)
> adds gauravburjwal.js

- README-PT-BR.md
Issues fixed:
- Formatting
- English text that was left inside the translation.
- Some untranslated text
> Small fixes to portuguese README

- peoples/jkingz.js
> Added my profile

- Rishabh000.js
- peoples/rishabh.js
> Add rishabh000.js

- peoples/lkarabeg.js
> Add my identity

- peoples/jx-willdo.js
> added jx-willdo

- peoples/manhalrahman.js
I am new to Github. I followed your instructions. 
Thanks
> add manhalrahman

- peoples/mgermaine93.js
Thanks for the practice with contributing to open source!
> Added mgermaine93.js

- peoples/tonn24.js
> Add tonn24.js

- peoples/mrwillbarnz.js
Added mrwillbarnz.js file, detailing my online presence, omitted Facebook and Linkedin values.
> Create mrwillbarnz profile

- peoples/github_Darshan-Subramanya.js
> github_Darshan-Subramanya.js

- peoples/maulana20.js
Signed-off-by: maulana <maulana20@versatech.co.id>
> add maulana20.js

- peoples/github_dsntr17.js
Adding my credentials as beginner.  Hope this worked!
> Adding my crendentials

- peoples/kamva9697.js
> My first commit

- peoples/Bellycose.js
Substituted name, username, email, and twitter. Facebook and Linkedin are set as none.
> Input data

- README-it.md
> Add Italian language for README.md

- github.sarehprice.js
Accidentally added a file first without to the people's folder but then I corrected and added it there.
> Add github.sarehprice.js

- peoples/mittu.js
> Added Mittu's Details

- peoples/singhambuj.js
Thank you for your guidance :)
> Please merge my pull request

- peoples/jatta-njie21.js
> My contribution

- peoples/github_Souvik48.js
> Added a file inside /peoples

- peoples/NOOB_AA.js
> added file in people folder

- peoples/Velocity9013.js
> add Velocity to peoples

- peoples/babul28.js
Getting started to contribute on open source project
- [✅] Follow @mazipan
- [✅] Push 🌟 button in this repository
> My first pull request to open source project

- peoples/github_ssamuk.js
-Created file wich is named after my GitHub account and inserted some information like my GitHub acoount name. Now I'm trying to create a pull request.
- [x ] Follow @mazipan
- [x ] Push 🌟 button in this repository
> OpenSource testing

- peoples/github_Zheng-1997.js
Creating new file for `@Zheng-1997`
> Added github_Zheng-1997.js file

- peoples/github_bereketsemagn.js
Creating new file for `@bereketsemagn`
> Added github_bereketsemagn.js file

- peoples/github Melik-A1422.js
> Create github Melik-A1422.js

- peoples/github_nivedita.js
> Add nivedita.js

- peoples/github_AntonioNtV.js
Creating new file for `@AntonioNtV`
> Creating new file for AntonioNtV

- peoples/github_marianavoimbra.js
Creating new file for `@marianacoimbra`
> Adding myself as person on this amazing repository

- peoples/test2020.js
- [ X ] Follow @mazipan
- [ X ] Push 🌟 button in this repository
> feat: checkin test PR

- peoples/github_sandiproybalitha.js
> my first contribution on github

- README-NL.md
> Add Dutch version of README.md

- peoples/github_ayushagarwal28.js
> Added ayush intro

- peoples/github_arunav11.js
> Added arunav to people

- peoples/github_abhpd.js
> Added github_abhpd.js

- peoples/rodrrj.js
Created a js file for the user rodrrj.
Used this repository to get a good refresher on creating pull requests after some time away.
Thank you!
> Add User Rodrrj

- peoples/User1.js
> Adding new file

- peoples/bloodymonkey.js
Contribution learning from bloodymonkey
> add-bloodymonkey

- pyGitHub7.js
> Tried to follow all the mentioned steps

- peoples/Inzamam.js
> Added my Info in React

- peoples/ajailani4
> add my pull request

- peoples/ChiranjeetMandal.js
> Code with identity

- peoples/sennahLesser.js
>  Create PR with adding your name to this repo #1

- peoples/purakoso.js
> add people/purakoso.js

- peoples/gaurav.js
> adding profile

- peoples/github_ayayace16.js
> add-ayayace16.js

- peoples/syedmuhammadabid.js
> My Profile added

- peoples/baktistr.js
halo mas mazipan..
dulu pernah baca blog mazipan yang dari pemalang, saya juga orang pemalang mas.
PR pertama seumur hidup.. salam kenal dan matur nuwun mas
> Hello, salam kenal mazipan, seko wong pemalang :)

- peoples/aufalmarom.js
> try to contribute oss

- peoples/cosaldi.js
> add-cosaldi.js

- peoples/trastanechora.js
> Add trastanechora.js

- peoples/qmohitsingh.js
> added info of qmohitsingh :tada:

- people/github_JesperKYH.js
> First Commit

- people/github_mkamra2000.js
Hi, I am new to open source and I open this pull request for only learning purposes.
> Created github_mkamra2000.js file

- people/github_payalpatra.js
> Added details to people

- people/github_cesarnina.js
> Created github_cesarnin.js

- people/github_vittorio.js
> Add Vittorio Rinaldo to People Folder

- people/github_adeyemiprofile.js
> Add my name

- Nagsenwaghmare.js
> Add Nagsen Waghmare To your contributors list

- people/SanskarMishra.js
> Add Nagasaki1

- people/imad-boudguigue.js
> add imad boudguigue to list

- people/thititongumpun.js
> firsttime pr

- people/martian1431.js
> My first pull request on github.

- people/MaliJetal.js
> my new post request

- people/masterbrian99.js
> add my details

- people/github.mero.js
> first cont.

- people/github_username.js
> add github_username.js

- people/github_username.js
> Updated module.exports

- people/github_username.js
> First time using of github repositories 

- people/github_username.js
- people/github_zx.js
> Added github_zx.js

- people/github_Marci0liveira.js
> Adding Spoonman's personal data

- people/github_Trend20.js
> first contribution

- people/github_rarief.js
> Add github_rarief.js

- people/github_username.js
> adding new user

- people/tr29038.js
> First open source

- people/aemzayn.js
> add new user

- github_kianfeng.js
Hi mazipan, thank you for doing this project. It surely boosted my confidence to contribute to other repos in the future. Your work is much appreciated.
> My first commit to open source projects

- pratiksha-dse.js
> Added a file containing personal info.

- people/github_username.js
- people/newfile.js
> Cfc mythrandir/add cfc mythrandir

- people/ip_contribution.js
> Added a file with data.

- people/hermansyah32.js
Thank you providing this repo for us to learn
> add-herman

- people/mdatif796.js
> adding mdatif796.js to people

- people/pablo-clueless.js
> -pablo-clueless-branch

- people/pablo-clueless.js
> Pablo clueless/add pablo clueless

- people/github_jcmurciap.js
- people/jcmurciap.js
Hello, 
I'm beginner here and i would like contribute to open source projects. Send me a message if my process is correct.
Thank you and have a nice day!
> added a new contributor branch

- people/ridlwan17.js
> add ridlwan17 in directory people

- people/courtneyzhan.js
> add courtneyzhan in directory

- people/HridoyHazard.js
> Added HridoyHazard

- peoples/agungardiyanta.js
> added my name

- people/mounil.js
- people/new-mounil.js
> First pull request

- people/inessa2020.js
> Adding Ness to the people folder

- people/github_kirti0223.js
> Kirti0223/add kirti.js

- people/github_ateetvmware.js
> add ateetvmware.js

- README-CHI.md
Hi, mazipan. I found this repo's Chinese version was translated by google translate. It's inaccurate in many places and is behind the English version, so I translate it myself. Hope you like it.
- [√] Follow @mazipan
- [√] Push 🌟 button in this repository
Thank you!
> Translate to Chinese

- people/serega4517.js
> added serega4517

- people/cw66786.js
> added myname.js file

- people/github_KrishChopra22.js
Before creating this PR, I've already finished these two things:
Thank you!
> added KrishChopra22 as a contributor

- package-lock.json
- people/Aryan-Jagadale.js
- people/Sukriti8877.js
- yarn.lock
> Started Open source

- people/adi.js
> Added adi.js in people directory

- README.md
> fixed spelling/grammar mistake

- manmohan4142.js
> Open source Contributer

- people/github_username.js
> My initial contribution.

- people/github_userinfo.js
> User info added

- people/Mouni.txt
> adding my name, my first commit

- people/manilkanav.js
> Add manilkanav.js

- people/panu.js
> Add Panu profiles

- people/github_devil.js
> added devil

- people/github_username.js
Listed my info in the github_username.js file.
Name, email, twitter and LinkedIn are updated.
> Changes in username

- people/github_naveengitboi.js
> added username naveengitboi

- people/github_amarjeetsahoo.js
> add-amarjeetsahoo

- people/github_AhorIsaac.js
> added AhorIsaac (#541)

- people/github_milan.js
> user name added

- people/TiagoRibeiro25.js
> Added TiagoRibeiro25.js

- people/github_yogi.js
> hello-open-source

- people/github_KyloRen04.js
> Added KyloRen04.js  to People

- people/github_vashafaris.js
> Add vashafaris to people

- people/remahmoud.js
> add remahmoud to people

- people/AmmarYasser.js
> Added a new file, people/AmmarYasser.js

- translations/README-FR.md
I have completed the full translation of the README into French to make the content more accessible to French-speaking users. Here are the changes I made:
Translated all the headings, sections, and paragraphs of the README into French.
Corrected grammar, syntax, and punctuation to ensure consistency and clarity in the translated text.
Added links to the translated versions of the README in other languages to facilitate user navigation.
I made sure that the translation remains faithful to the original while adhering to the standards of the French language. I hope this contribution will be helpful to French-speaking users in the community.
Thank you!
Signed-off-by: moasko [moasko.dev@gmail.com)](mailto:moasko.dev@gmail.com)
> DOCS:Translation of README into French

- people/github_francis.js
- yarn.lock
> Added my file to the project

- people/github_janelaxag.js
> add person

- people/arenodi.js
- [x ] Follow @mazipan
Thank you!
> Adding 'arenodi.js' file to 'people' folder

- people/github_fjean0522.js
> Add & update github_fjean0522.js file.

- people/Pratik1968.js
> added Pratik1968.js file

- people/Nishan9t.js
> added Nisha9t

- people/khojiManjhi.js
> Created khojiManjhi.js

- people/Happy-Singh.js
---
name: 'Adding YourName'
about: Adding new file under people directory
title: 'CHORE: Adding [YourName]'
labels: automerge
assignees: mazipan
---
@mazipan 
Could you review and merge it?
Hi, here we go. I am adding name to this repo.
Thank you!
> Added Profile

- people/AashikBharti.js
> Add AashikBharti

- people/SakshamBhugra.js
> Added SakshamBhugra.js

- people/Rohan-Kumar.js
> Created js file

- people/Suresh.js
> Addded my profile

- people/vidhijain.js
- vidhijain.js
> vidhijain.js

- people/amandeep-singh-parihar.js
> amandeepsinghparihar

- people/amitverma.js
> updated my profile

- people/0x00zer0day.js
Before creating this PR, please do these two things:
Thank you!
> Added User Info

- people/madjiebimaa.js
> Add madjiebimaa.js file

- people/AvinavCHATTERJEE2103028.js
> addedjsfile

- people/ankoorgorai.js
> profileAdded

- people/github_amitverma147.js
> updated people

- people/shubham-vartak.js
> Added my name to the repository

- people/Shubhamkyup
> Added new person in people

- vidhijain.js
> Corrected vidhijain.js

- people/harshal.js
> updated the changes

- people/upendra.js
Hi, here we go. I am adding Upendra to this repo.
Thank you!
> added upendra.js

- people/upendra.js
Hi, here we go. I am adding upendra to this repo.
Thank you!
> add upendra

- people/Abhiram.js
> add dragon

- people/tmsagar.js
> Add tmsagar

- people/0Armaan025.js
Please help me to review and merge it.
Thank you!
> added 0Armaan025.js

- people/mehul.js
> add - Mehul

- people/AryadipMridha.js
> Hello Open World

- people/Codedrinks270.js
> Added Codedrinks270.js

- people/Khushminder270.js
> Adding Khushminder270.js

- people/Sure.js
> Created Sure.js

- translations/README-HINGLISH.md
Added Hinglish translation for README
its like Hindi + English, Spoken in India
Thank you!
> Added Hinglish translation

- README.md
Added Hinglish translation for README
its like Hindi + English, Spoken in India
#673 
Thank you!
> README.md: added Hinglish

- people/AmanPathan.js
Added my profile links and details.
Thank you!
> Created and Profile Details AmanPathan.js

- people/A-viralS.js
> Created A-viralS.js

- people/add-sudhanshu-77.js
> add-sudhanshu-77.js

- people/jahnavithutta.js
> add-jahnavi

- people/Viper.js
> Added Viper.js

- people/Priyanshuthapliyal2005.js
> Add Priyanshuthapliyal2005.js file

- people/HVbajoria.js
> Created HVbajoria.js

- people/codeOraaange.js
> add: codeOraaange

- people/vidyaa18.js
> Add vidyaa18

- people/github_username.js
> feat: add github_username.js

- people/lisa.js
> Added lisa.js

- people/jeeehaan.js
> feat: add jeeehaan

- people/Yash.js
> Adding Yash

- people/vivek.js
> Add vivekghori

- people/nirju.js
> Added nirju.js

- people/thesuaveguy.js
> Added thesuaveguy.js in people directory

- people/sabarinathan07.js
> learn open source

- people/Harsha-10.js
> added a name

- README.md
- translations/README-HU.md
In this Pull request, I have added Hungarian translation of README.md file and the link to it in the file. 
Thank you!
> Added Hungarian Translation 

- people/prasanna1225.js
> updated my details

- people/elfajriharsuda.js
> added elfajriharsuda.js

- people/github_username.js
> This is my first pull request!

- people/prasannakumarboddeda02.js
> prasannakumarboddeda02

- people/github_username.js
> Add-MohamedBoukthir

- people/favy-codez.js
> added name 

- people/github_username.js
> Thanks to you all,first time trying this haaa

- people/ekaterine_sheshelidze.js
> file added

- people/github_soufianeouk.js
> feat: add github_soufianeouk.js

- people/github_alrakib1.js
> Added alrakib1.js file on people folder

- people/github_sukumar.js
> added js file to people directory

- people/github_isaac-whiz.js
Hi, here we go. I am adding Isaac Whiz to this repo.
Thank you!
> Added Isaac Whiz social media links

- people/Muhammad-Azhy.js
> Added Muhammad Azhy

- people/Gumaan-Mahar.js
> Add Gumaan-Mahar.js

- people/emdadhossain25.js
> added emdad hossain to people directory

- people/jaebee2.js
> jaebee2.js

- people/github_theskd.js
> added my file to people directory

- .vscode/settings.json
- people/github_JasrajChouhan.js
> (Add) : my information in github_JasrajChouhan.js file

- people/github_MadugulaNaveen.js
> Add github_MadugulaNaveen.js to People Directory

- people/github_vnavaneeth10.js
> added a new file 

- README.md
> CHORE: Add contributors

- people/aadameiaa.js
> added me to people directory

- people/github_sabbir.js
> add new commit here

- people/LinaAitIder.js
> add-LinaAitIder

- people/rcd_env.js
> add my file

- people/moecute-asmr.js
> Add moecute-asmr profile

- people/github_kironroy.js
> Add Kiron Roy to hello-open-source.
